### ISSUE TITLE
"Not compatible with the latest version of Ulauncher" 

### ISSUE THREAD

**Issue by NotAkitake** [buty4649/ulauncher-firefox-bookmarks#1]
![Screenshot from 2019-07-03 12-27-59](https://user-images.githubusercontent.com/7873528/60584656-4ffd8b80-9d7d-11e9-8006-8e9c166d250d.png)

**Comment by varac** [comment]
```
Okt 27 23:11:38 box ulauncher[29425]: 2019-10-27 23:11:38,246 | WARNING | ulauncher.api.server.GithubExtension: _read_json() | _read_json("master", "versions.json") failed. HTTPError: HTTP Error 404: Not Found
Okt 27 23:11:38 box ulauncher[29425]: 2019-10-27 23:11:38,246 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | GithubExtensionError: Could not find versions.json file using URL "https://raw.githubusercontent.com/buty4649/ulauncher-firefox-bookmarks/master/versions.json"
```

**Comment by buty4649** [comment]
Thank you for reporting me.
Fixed in master branch.

However, it seems that Firefox does not work well because it locks places.sqlite 😟

**Comment by buty4649** [comment]
fix in https://github.com/buty4649/ulauncher-firefox-bookmarks/commit/7e846749312748482cc535949913ca8997ed168e

**Comment by varac** [comment]
I still can't add this extension. I get:

```
Nov 15 22:05:14 box ulauncher[4229]: 2019-11-15 22:05:14,435 | ERROR | ulauncher.ui.windows.PreferencesUlauncherDialog: on_scheme_callback() | Unexpected API error. JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 5 (char 6)
Nov 15 22:05:14 box ulauncher[4229]: Traceback (most recent call last):
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 192, in on_scheme_callback
Nov 15 22:05:14 box ulauncher[4229]:     resp = rt.dispatch(self, scheme_request.get_uri())
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3/dist-packages/ulauncher/utils/Router.py", line 49, in dispatch
Nov 15 22:05:14 box ulauncher[4229]:     return callback(context, url_params)
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py", line 400, in prefs_extension_add
Nov 15 22:05:14 box ulauncher[4229]:     ext_id = downloader.download(url)
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3/dist-packages/ulauncher/api/server/ExtensionDownloader.py", line 75, in download
Nov 15 22:05:14 box ulauncher[4229]:     commit = gh_ext.find_compatible_version()
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 71, in find_compatible_version
Nov 15 22:05:14 box ulauncher[4229]:     for ver in self.read_versions():
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 110, in read_versions
Nov 15 22:05:14 box ulauncher[4229]:     versions = self._read_json('master', 'versions.json')
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3/dist-packages/ulauncher/api/server/GithubExtension.py", line 101, in _read_json
Nov 15 22:05:14 box ulauncher[4229]:     return json.loads(urlopen(url).read().decode('utf-8'))
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
Nov 15 22:05:14 box ulauncher[4229]:     return _default_decoder.decode(s)
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
Nov 15 22:05:14 box ulauncher[4229]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Nov 15 22:05:14 box ulauncher[4229]:   File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
Nov 15 22:05:14 box ulauncher[4229]:     obj, end = self.scan_once(s, idx)
Nov 15 22:05:14 box ulauncher[4229]: json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 5 (char 6)<Paste>

```

**Comment by varac** [comment]
`versions.json` contains invalid json:

```
❯ curl -s https://raw.githubusercontent.com/buty4649/ulauncher-firefox-bookmarks/master/versions.json | jq .
parse error: Objects must consist of key:value pairs at line 3, column 1

❯ curl -s https://raw.githubusercontent.com/kbialek/ulauncher-bitwarden/master/versions.json | jq .
[
  {
    "required_api_version": "^2.0.0",
    "commit": "master"
  }
]
```

**Comment by buty4649** [comment]
@varac 
Thank you for teaching me.fix in https://github.com/buty4649/ulauncher-firefox-bookmarks/commit/f794d545451a2656448e444017472c7ea1c9dc1e
Try it again.

**Comment by varac** [comment]
I confirm it works now !
